# - name: "Check if bouncer {{ cs_bouncer }} is installed"
#   ansible.builtin.stat:
#     path: "{{ cs_install_dir_bouncer }}/{{ cs_bouncer }}"
#   register: bouncer_stat

# - name: Check if crowdsec agent is installed and return version
#   ansible.utils.cli_parse:
#     command: crowdsec -version
#     parser:
#       name: ansible.netcommon.native
#       template_path: cs-version.yml
#     set_fact: crowdsec_version
#   when: bouncer_stat.stat.exists

- debug:
    msg: "TBD"