- name: Check if crowdsec agent is installed
  ansible.builtin.stat:
    path: "{{ cs_install_dir_agent }}/crowdsec"
  register: crowdsec_stat

# - name: Check version of crowdsec agent
#   ansible.utils.cli_parse:
#     command: crowdsec -version
#     parser:
#       name: ansible.netcommon.native
#       os: linux
#     set_fact: crowdsec_version
#   when: crowdsec_stat.stat.exists

- name: Unarchive {{ cs_download_baseurl }}/{{ cs_agent_version }}/{{ cs_tarball }} to {{ cs_install_target_dir }}
  ansible.builtin.unarchive:
    src: "{{ cs_download_baseurl }}/{{ cs_agent_version }}/{{ cs_tarball }}"
    dest: "{{ cs_install_target_dir }}"
    keep_newer: yes
    remote_src: yes
  when: not crowdsec_stat.stat.exists # or version differs

- name: Install crowdsec in unattended mode
  ansible.builtin.command: "./wizard.sh --unattended"
  args:
    chdir: "{{ cs_install_target_dir }}/crowdsec-{{ cs_agent_version }}/"
  register: install_output
  when: not crowdsec_stat.stat.exists # or version differs
  become: true

- name: Upgrade crowdsec
  ansible.builtin.command: "./wizard.sh --upgrade"
  args:
    chdir: "{{ cs_install_target_dir }}/crowdsec-{{ cs_agent_version }}/"
  register: upgrade_output
  when: crowdsec_stat.stat.exists
  become: true
