---
# tasks file for papanito.crowdsec

- name: Install crowdsec agent (Debian)
  ansible.builtin.import_tasks: install_agent_debian.yml
  when: cs_install_agent|bool and ansible_os_family == 'Debian'
  tags:
    - agent

- name: Install crowdsec agent (Enterprise Linux)
  ansible.builtin.import_tasks: install_agent_rhel.yml
  when: cs_install_agent|bool and ansible_os_family == 'RedHat'
  tags:
    - agent

- name: Install crowdsec agent (tarball)
  ansible.builtin.import_tasks: install_agent_tarball.yml
  when: cs_install_agent|bool and ansible_os_family != 'Debian' and ansible_os_family != 'RedHat'
  tags:
    - agent

- name: Enroll instance to console
  ansible.builtin.command: "cscli console enroll {{ cs_console_token }}"
  when: cs_console_token is defined
  tags:
    - console

- name: Install bouncers (Debian)
  ansible.builtin.include_tasks: install_bouncers_debian.yml
  loop: "{{ cs_bouncers | dict2items }}"
  loop_control:
    loop_var: cs_bouncer
  when: cs_bouncers is defined and ansible_os_family == 'Debian'
  tags:
    - bouncers

- name: Install bouncers (RedHat)
  ansible.builtin.include_tasks: install_bouncers_rhel.yml
  loop: "{{ cs_bouncers | dict2items }}"
  loop_control:
    loop_var: cs_bouncer
  when: cs_bouncers is defined and ansible_os_family == 'RedHat'
  tags:
    - bouncers

- name: Install bouncers (tarball)
  ansible.builtin.include_tasks: install_bouncers_tarball.yml
  loop: "{{ cs_bouncers | dict2items }}"
  loop_control:
    loop_var: cs_bouncer
  when: cs_bouncers is defined and ansible_os_family != 'Debian' and ansible_os_family != 'RedHat'
  tags:
    - bouncers
